spring.application.name=notesproject

spring.datasource.url=jdbc:mysql://localhost:3306/notesdb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=prashant@2006

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#this line is use to show exception msg in postman , but this not good 
#spring.web.error.include-message = always